// flow-typed signature: 26d41f31164d98b65b78e11fbae55eb5
// flow-typed version: <<STUB>>/colors.css_v3.0.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'colors.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'colors.css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'colors.css/js/colors' {
  declare module.exports: any;
}

// Filename aliases
declare module 'colors.css/js/colors.js' {
  declare module.exports: $Exports<'colors.css/js/colors'>;
}
