// flow-typed signature: 4e7248ac3bbc8f415f6fe242e8eab64a
// flow-typed version: <<STUB>>/gatsby-plugin-emotion_v4.0.3/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-emotion'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-emotion' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-emotion/gatsby-node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-emotion/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-emotion/gatsby-node'>;
}
declare module 'gatsby-plugin-emotion/index' {
  declare module.exports: $Exports<'gatsby-plugin-emotion'>;
}
declare module 'gatsby-plugin-emotion/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-emotion'>;
}
