// flow-typed signature: 825efe5c950041d51929014a676f5c0e
// flow-typed version: <<STUB>>/gatsby-remark-prismjs_v2.0.5/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-remark-prismjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-remark-prismjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-remark-prismjs/dist/highlight-code' {
  declare module.exports: any;
}

declare module 'gatsby-remark-prismjs/dist/index' {
  declare module.exports: any;
}

declare module 'gatsby-remark-prismjs/dist/load-prism-language' {
  declare module.exports: any;
}

declare module 'gatsby-remark-prismjs/dist/parse-line-number-range' {
  declare module.exports: any;
}

declare module 'gatsby-remark-prismjs/highlight-code' {
  declare module.exports: any;
}

declare module 'gatsby-remark-prismjs/load-prism-language' {
  declare module.exports: any;
}

declare module 'gatsby-remark-prismjs/parse-line-number-range' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-remark-prismjs/dist/highlight-code.js' {
  declare module.exports: $Exports<'gatsby-remark-prismjs/dist/highlight-code'>;
}
declare module 'gatsby-remark-prismjs/dist/index.js' {
  declare module.exports: $Exports<'gatsby-remark-prismjs/dist/index'>;
}
declare module 'gatsby-remark-prismjs/dist/load-prism-language.js' {
  declare module.exports: $Exports<'gatsby-remark-prismjs/dist/load-prism-language'>;
}
declare module 'gatsby-remark-prismjs/dist/parse-line-number-range.js' {
  declare module.exports: $Exports<'gatsby-remark-prismjs/dist/parse-line-number-range'>;
}
declare module 'gatsby-remark-prismjs/highlight-code.js' {
  declare module.exports: $Exports<'gatsby-remark-prismjs/highlight-code'>;
}
declare module 'gatsby-remark-prismjs/index' {
  declare module.exports: $Exports<'gatsby-remark-prismjs'>;
}
declare module 'gatsby-remark-prismjs/index.js' {
  declare module.exports: $Exports<'gatsby-remark-prismjs'>;
}
declare module 'gatsby-remark-prismjs/load-prism-language.js' {
  declare module.exports: $Exports<'gatsby-remark-prismjs/load-prism-language'>;
}
declare module 'gatsby-remark-prismjs/parse-line-number-range.js' {
  declare module.exports: $Exports<'gatsby-remark-prismjs/parse-line-number-range'>;
}
