// flow-typed signature: 3309460023ea4a2bbff3949b805807fa
// flow-typed version: <<STUB>>/gatsby-mdx_v0.2.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-mdx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-mdx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-mdx/component-with-mdx-scope' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/constants' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/context' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/feed' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/gatsby/create-webpack-config' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/gatsby/extend-node-type' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/gatsby/on-create-node' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/gatsby/on-create-page' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/gatsby/preprocess-source' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/loaders/mdx-loader' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/mdx-renderer' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/utils/create-fake-file-node' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/utils/create-mdx-node' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/utils/default-options' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/utils/extract-exports' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/utils/gen-mdx' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/utils/get-source-plugins-as-remark-plugins' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/utils/get-table-of-content' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/utils/mdx' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-mdx/component-with-mdx-scope.js' {
  declare module.exports: $Exports<'gatsby-mdx/component-with-mdx-scope'>;
}
declare module 'gatsby-mdx/constants.js' {
  declare module.exports: $Exports<'gatsby-mdx/constants'>;
}
declare module 'gatsby-mdx/context.js' {
  declare module.exports: $Exports<'gatsby-mdx/context'>;
}
declare module 'gatsby-mdx/feed.js' {
  declare module.exports: $Exports<'gatsby-mdx/feed'>;
}
declare module 'gatsby-mdx/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-mdx/gatsby-node'>;
}
declare module 'gatsby-mdx/gatsby/create-webpack-config.js' {
  declare module.exports: $Exports<'gatsby-mdx/gatsby/create-webpack-config'>;
}
declare module 'gatsby-mdx/gatsby/extend-node-type.js' {
  declare module.exports: $Exports<'gatsby-mdx/gatsby/extend-node-type'>;
}
declare module 'gatsby-mdx/gatsby/on-create-node.js' {
  declare module.exports: $Exports<'gatsby-mdx/gatsby/on-create-node'>;
}
declare module 'gatsby-mdx/gatsby/on-create-page.js' {
  declare module.exports: $Exports<'gatsby-mdx/gatsby/on-create-page'>;
}
declare module 'gatsby-mdx/gatsby/preprocess-source.js' {
  declare module.exports: $Exports<'gatsby-mdx/gatsby/preprocess-source'>;
}
declare module 'gatsby-mdx/index' {
  declare module.exports: $Exports<'gatsby-mdx'>;
}
declare module 'gatsby-mdx/index.js' {
  declare module.exports: $Exports<'gatsby-mdx'>;
}
declare module 'gatsby-mdx/loaders/mdx-loader.js' {
  declare module.exports: $Exports<'gatsby-mdx/loaders/mdx-loader'>;
}
declare module 'gatsby-mdx/mdx-renderer.js' {
  declare module.exports: $Exports<'gatsby-mdx/mdx-renderer'>;
}
declare module 'gatsby-mdx/utils/create-fake-file-node.js' {
  declare module.exports: $Exports<'gatsby-mdx/utils/create-fake-file-node'>;
}
declare module 'gatsby-mdx/utils/create-mdx-node.js' {
  declare module.exports: $Exports<'gatsby-mdx/utils/create-mdx-node'>;
}
declare module 'gatsby-mdx/utils/default-options.js' {
  declare module.exports: $Exports<'gatsby-mdx/utils/default-options'>;
}
declare module 'gatsby-mdx/utils/extract-exports.js' {
  declare module.exports: $Exports<'gatsby-mdx/utils/extract-exports'>;
}
declare module 'gatsby-mdx/utils/gen-mdx.js' {
  declare module.exports: $Exports<'gatsby-mdx/utils/gen-mdx'>;
}
declare module 'gatsby-mdx/utils/get-source-plugins-as-remark-plugins.js' {
  declare module.exports: $Exports<'gatsby-mdx/utils/get-source-plugins-as-remark-plugins'>;
}
declare module 'gatsby-mdx/utils/get-table-of-content.js' {
  declare module.exports: $Exports<'gatsby-mdx/utils/get-table-of-content'>;
}
declare module 'gatsby-mdx/utils/mdx.js' {
  declare module.exports: $Exports<'gatsby-mdx/utils/mdx'>;
}
