// flow-typed signature: 03b25d3947d126f52fe9972fb8455d08
// flow-typed version: <<STUB>>/gatsby-plugin-twitter_v2.0.7/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-twitter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-twitter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-twitter/gatsby-browser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-twitter/gatsby-browser.js' {
  declare module.exports: $Exports<'gatsby-plugin-twitter/gatsby-browser'>;
}
declare module 'gatsby-plugin-twitter/index' {
  declare module.exports: $Exports<'gatsby-plugin-twitter'>;
}
declare module 'gatsby-plugin-twitter/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-twitter'>;
}
