// flow-typed signature: fd9f5f2af1097e97f0810cfe6b95545e
// flow-typed version: <<STUB>>/gatsby-remark-responsive-iframe_v2.0.6/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-remark-responsive-iframe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-remark-responsive-iframe' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gatsby-remark-responsive-iframe/index' {
  declare module.exports: $Exports<'gatsby-remark-responsive-iframe'>;
}
declare module 'gatsby-remark-responsive-iframe/index.js' {
  declare module.exports: $Exports<'gatsby-remark-responsive-iframe'>;
}
