// flow-typed signature: eaa7333f6c7c1c01c480bcb8b74b84d5
// flow-typed version: <<STUB>>/gatsby-plugin-feed_v1.3.20/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-feed'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-feed' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-feed/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-feed/gatsby-ssr' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-feed/internals' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-feed/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-feed/gatsby-node'>;
}
declare module 'gatsby-plugin-feed/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-plugin-feed/gatsby-ssr'>;
}
declare module 'gatsby-plugin-feed/index' {
  declare module.exports: $Exports<'gatsby-plugin-feed'>;
}
declare module 'gatsby-plugin-feed/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-feed'>;
}
declare module 'gatsby-plugin-feed/internals.js' {
  declare module.exports: $Exports<'gatsby-plugin-feed/internals'>;
}
