// flow-typed signature: 34badebe2be3b729c1dc480847a7a876
// flow-typed version: <<STUB>>/gatsby-plugin-klipse_v2.1.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-klipse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-klipse' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-klipse/gatsby-browser' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-klipse/gatsby-ssr' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-klipse/gatsby-browser.js' {
  declare module.exports: $Exports<'gatsby-plugin-klipse/gatsby-browser'>;
}
declare module 'gatsby-plugin-klipse/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-plugin-klipse/gatsby-ssr'>;
}
declare module 'gatsby-plugin-klipse/index' {
  declare module.exports: $Exports<'gatsby-plugin-klipse'>;
}
declare module 'gatsby-plugin-klipse/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-klipse'>;
}
