// flow-typed signature: 3cd0ef6b7197496ce1a4bd12e37e4926
// flow-typed version: <<STUB>>/gatsby-remark-copy-linked-files_v1.5.30/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-remark-copy-linked-files'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-remark-copy-linked-files' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gatsby-remark-copy-linked-files/index' {
  declare module.exports: $Exports<'gatsby-remark-copy-linked-files'>;
}
declare module 'gatsby-remark-copy-linked-files/index.js' {
  declare module.exports: $Exports<'gatsby-remark-copy-linked-files'>;
}
