// flow-typed signature: a68a3627b388274445131ed6e8dbf224
// flow-typed version: <<STUB>>/gatsby-plugin-remove-serviceworker_v1.0.0/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-remove-serviceworker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-remove-serviceworker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-remove-serviceworker/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-remove-serviceworker/sw' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-remove-serviceworker/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-remove-serviceworker/gatsby-node'>;
}
declare module 'gatsby-plugin-remove-serviceworker/index' {
  declare module.exports: $Exports<'gatsby-plugin-remove-serviceworker'>;
}
declare module 'gatsby-plugin-remove-serviceworker/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-remove-serviceworker'>;
}
declare module 'gatsby-plugin-remove-serviceworker/sw.js' {
  declare module.exports: $Exports<'gatsby-plugin-remove-serviceworker/sw'>;
}
