// flow-typed signature: a67f4bfdd51b2082589e417b3b6b11ac
// flow-typed version: <<STUB>>/gatsby-plugin-twitter_v1.0.20/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-twitter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-twitter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-twitter/gatsby-browser' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-twitter/gatsby-ssr' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-twitter/gatsby-browser.js' {
  declare module.exports: $Exports<'gatsby-plugin-twitter/gatsby-browser'>;
}
declare module 'gatsby-plugin-twitter/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-plugin-twitter/gatsby-ssr'>;
}
declare module 'gatsby-plugin-twitter/index' {
  declare module.exports: $Exports<'gatsby-plugin-twitter'>;
}
declare module 'gatsby-plugin-twitter/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-twitter'>;
}
