// flow-typed signature: 1aac7da583f388d0fc16676fac0dfd82
// flow-typed version: <<STUB>>/gatsby-plugin-react-helmet_v2.0.11/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-react-helmet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-react-helmet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-react-helmet/gatsby-ssr' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-react-helmet/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-plugin-react-helmet/gatsby-ssr'>;
}
declare module 'gatsby-plugin-react-helmet/index' {
  declare module.exports: $Exports<'gatsby-plugin-react-helmet'>;
}
declare module 'gatsby-plugin-react-helmet/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-react-helmet'>;
}
