// flow-typed signature: 0d80eae998bc38cd543af15217bdf214
// flow-typed version: <<STUB>>/gatsby-remark-smartypants_v1.4.12/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-remark-smartypants'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-remark-smartypants' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gatsby-remark-smartypants/index' {
  declare module.exports: $Exports<'gatsby-remark-smartypants'>;
}
declare module 'gatsby-remark-smartypants/index.js' {
  declare module.exports: $Exports<'gatsby-remark-smartypants'>;
}
