// flow-typed signature: d907970826428e0dfd5283a2911f805d
// flow-typed version: <<STUB>>/gatsby-link_v1.6.46/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-link'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-link' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-link/__tests__/index' {
  declare module.exports: any;
}

declare module 'gatsby-link/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-link/__tests__/index.js' {
  declare module.exports: $Exports<'gatsby-link/__tests__/index'>;
}
declare module 'gatsby-link/dist/index.js' {
  declare module.exports: $Exports<'gatsby-link/dist/index'>;
}
declare module 'gatsby-link/index' {
  declare module.exports: $Exports<'gatsby-link'>;
}
declare module 'gatsby-link/index.js' {
  declare module.exports: $Exports<'gatsby-link'>;
}
