// flow-typed signature: 6fbe9fb630d2329a9dd797088b98b6fc
// flow-typed version: <<STUB>>/netlify-lambda_v1.0.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'netlify-lambda'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'netlify-lambda' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'netlify-lambda/bin/cmd' {
  declare module.exports: any;
}

declare module 'netlify-lambda/lib/build' {
  declare module.exports: any;
}

declare module 'netlify-lambda/lib/config' {
  declare module.exports: any;
}

declare module 'netlify-lambda/lib/serve' {
  declare module.exports: any;
}

// Filename aliases
declare module 'netlify-lambda/bin/cmd.js' {
  declare module.exports: $Exports<'netlify-lambda/bin/cmd'>;
}
declare module 'netlify-lambda/lib/build.js' {
  declare module.exports: $Exports<'netlify-lambda/lib/build'>;
}
declare module 'netlify-lambda/lib/config.js' {
  declare module.exports: $Exports<'netlify-lambda/lib/config'>;
}
declare module 'netlify-lambda/lib/serve.js' {
  declare module.exports: $Exports<'netlify-lambda/lib/serve'>;
}
