// flow-typed signature: 4be4b4bc6026dfcd521135fc0e66d9cf
// flow-typed version: <<STUB>>/prism-themes_v1.0.1/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prism-themes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prism-themes' {
  declare module.exports: any;
}
