// flow-typed signature: 741a79f4140646d271935092bf88c42b
// flow-typed version: <<STUB>>/@babel/preset-typescript_v7.1.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/preset-typescript'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/preset-typescript' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/preset-typescript/lib/index' {
  declare module.exports: any;
}

declare module '@babel/preset-typescript/src/index' {
  declare module.exports: any;
}

declare module '@babel/preset-typescript/test/fixtures/flow-compat/js-invalid/input' {
  declare module.exports: any;
}

declare module '@babel/preset-typescript/test/fixtures/flow-compat/js-valid/input' {
  declare module.exports: any;
}

declare module '@babel/preset-typescript/test/fixtures/flow-compat/js-valid/output' {
  declare module.exports: any;
}

declare module '@babel/preset-typescript/test/fixtures/flow-compat/ts-valid/output' {
  declare module.exports: any;
}

declare module '@babel/preset-typescript/test/fixtures/flow-compat/tsx-valid/output' {
  declare module.exports: any;
}

declare module '@babel/preset-typescript/test/fixtures/jsx-compat/js-valid/input' {
  declare module.exports: any;
}

declare module '@babel/preset-typescript/test/fixtures/jsx-compat/js-valid/output' {
  declare module.exports: any;
}

declare module '@babel/preset-typescript/test/fixtures/jsx-compat/tsx-valid/output' {
  declare module.exports: any;
}

declare module '@babel/preset-typescript/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/preset-typescript/lib/index.js' {
  declare module.exports: $Exports<'@babel/preset-typescript/lib/index'>;
}
declare module '@babel/preset-typescript/src/index.js' {
  declare module.exports: $Exports<'@babel/preset-typescript/src/index'>;
}
declare module '@babel/preset-typescript/test/fixtures/flow-compat/js-invalid/input.js' {
  declare module.exports: $Exports<'@babel/preset-typescript/test/fixtures/flow-compat/js-invalid/input'>;
}
declare module '@babel/preset-typescript/test/fixtures/flow-compat/js-valid/input.js' {
  declare module.exports: $Exports<'@babel/preset-typescript/test/fixtures/flow-compat/js-valid/input'>;
}
declare module '@babel/preset-typescript/test/fixtures/flow-compat/js-valid/output.js' {
  declare module.exports: $Exports<'@babel/preset-typescript/test/fixtures/flow-compat/js-valid/output'>;
}
declare module '@babel/preset-typescript/test/fixtures/flow-compat/ts-valid/output.js' {
  declare module.exports: $Exports<'@babel/preset-typescript/test/fixtures/flow-compat/ts-valid/output'>;
}
declare module '@babel/preset-typescript/test/fixtures/flow-compat/tsx-valid/output.js' {
  declare module.exports: $Exports<'@babel/preset-typescript/test/fixtures/flow-compat/tsx-valid/output'>;
}
declare module '@babel/preset-typescript/test/fixtures/jsx-compat/js-valid/input.js' {
  declare module.exports: $Exports<'@babel/preset-typescript/test/fixtures/jsx-compat/js-valid/input'>;
}
declare module '@babel/preset-typescript/test/fixtures/jsx-compat/js-valid/output.js' {
  declare module.exports: $Exports<'@babel/preset-typescript/test/fixtures/jsx-compat/js-valid/output'>;
}
declare module '@babel/preset-typescript/test/fixtures/jsx-compat/tsx-valid/output.js' {
  declare module.exports: $Exports<'@babel/preset-typescript/test/fixtures/jsx-compat/tsx-valid/output'>;
}
declare module '@babel/preset-typescript/test/index.js' {
  declare module.exports: $Exports<'@babel/preset-typescript/test/index'>;
}
